---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(plotly)
library(shiny)
library(rsconnect)
LA <- read_csv("./data/LA.csv")
```

```{r, echo = FALSE, results = "hide"}
# dashboard 1
crime <- LA %>%
  separate(premis_desc, into = c("Col1", "Col2"), sep = " - ", extra = "merge") %>%
  select(-Col2)

crime_prem <- crime

crime_lat = crime|>
  filter(lat!= 0,
         lon!= 0)
prem_summary <- crime_prem |>
  group_by(Col1) |>
  summarise(TotalCrimes = n(),
            Totalserious = sum(part_1_2 == 1),
            Totalnotserious = sum(part_1_2 == 2)) %>%
  arrange(desc(TotalCrimes))
top_prem <- prem_summary %>%
  mutate(Col1 = ifelse(row_number() > 20, "OTHERS", Col1)) %>%
  group_by(Col1) %>%
  summarise(TotalCrimes = sum(TotalCrimes),
            Serious = sum(Totalserious),
            Not_serious = sum(Totalnotserious)) %>%
  arrange(desc(TotalCrimes))

top_prem|>
  pivot_longer(
    cols = c(Serious, Not_serious), 
    names_to = "CrimeType", values_to = "Count"
  )

crime_type = crime_prem|>
  mutate(Col1 = if_else(Col1 %in% top_prem$Col1, Col1, 'OTHERS'))
```

```{r}
# dashboard 2
data2 <- LA
data2 = data2 |>
  select(dr_no ,date = date_occ, time = time_occ, area = area_name, severity = part_1_2, crime_type = crm_cd_desc, premis = premis_desc) |>
  mutate(
    severity = case_when(
      severity == 1 ~ "serious",
      severity == 2 ~ "less serious"
    ) )|>
  mutate(severity = factor(severity, levels = c("less serious", "serious"), ordered = TRUE),
         crime_type = tolower(crime_type))

data2 = data2 |>
  mutate(date = as.Date(sub(" .*", "", data2$date), format = "%m/%d/%Y"))
data2$time = sprintf("%04s", as.character(data2$time))
data2$time = format(strptime(data2$time, format="%H%M"), "%H:%M")

data2 = data2 |>
  mutate(
    year_month = floor_date(data2$date, unit = "month"),
    month = month(date),
    season = case_when(
      month %in% 3:5 ~ "Spring",
      month %in% 6:8 ~ "Summer",
      month %in% 9:11 ~ "Fall",
      month %in% c(12,1,2) ~ "Winter",
      TRUE ~ "Unknown"
    ),
    hour = sub(":(.*)", "", data2$time),
    year = year(date),
    weekday = wday(date, label = TRUE, abbr = FALSE)
  )

```

```{r}
# dashboard 3
# Notice that age 0 stands for NA
data3 <- LA
data3$vict_age[data3$vict_age == 0] <- NA

# divide age into four categories
data3$age_group <- cut(
  data3$vict_age,
  breaks = c(-Inf, 18, 40, 60, Inf),
  labels = c("juvenile", "Young adult", "Middle-aged people", "The elderly"),
  right = FALSE
)

data3$severity_label <- ifelse(data3$part_1_2 == 1, "Serious", "Less Serious")

# turn severity into factor
data3$severity_label <- as.factor(data3$severity_label)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
# Sidebar for filters
selectInput(
  inputId = "filter_area",
  label = "Select Area:",
  choices = unique(LA$area_name),
  selected = unique(LA$area_name)[1]
)

# Additional filter for Chart B
selectInput(
  inputId = "victim_time",
  label = "Select Time Trend:",
  choices = c("Seasonal", "Weekday", "Hourly"),
  selected = "Seasonal"
)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
  filtered_data <- crime %>%
    filter(
      lat != 0,
      lon != 0,
      area_name == input$filter_area
    ) %>%
    mutate(
      text_label = str_c(
        "Area: ", area_name, "\nPremises: ", Col1,
        "\nSerious Level: ", part_1_2, "\nStatus: ", status_desc
      )
    )

  plot_ly(
    data = filtered_data,
    x = ~lat, y = ~lon, type = "scatter", mode = "markers",
    color = ~factor(status_desc), alpha = 0.6, text = ~text_label,
    marker = list(size = 4)
  ) %>%
    layout(
      title = paste("Crime Location Scatter Plot in", input$filter_area),
      xaxis = list(title = "Latitude"),
      yaxis = list(title = "Longitude")
    )
})
```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  filtered_data <- data2 %>%
    filter(area == input$filter_area)

  if (nrow(filtered_data) == 0) {
    return(ggplotly(ggplot() + labs(title = "No Data Available for Selected Area")))
  }

 if (input$victim_time == "Seasonal") {
    seasonal_data <- filtered_data %>%
      mutate(season = factor(season, levels = c("Spring", "Summer", "Fall", "Winter"))) |>
      group_by(season) %>%
      summarise(season_count = n()) %>%
      ggplot(aes(x = season, y = season_count)) +
      geom_point(color = "green") +
      geom_line(size = 0.5, alpha = 0.7, color = "green") +
      labs(title = "Crime Counts by Season", x = "Season", y = "Count") +
      theme_minimal()

    ggplotly(seasonal_data)

  } else if (input$victim_time == "Weekday") {
    weekday_data <- filtered_data %>%
      mutate(weekday = factor(weekday, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))) %>%
      group_by(weekday) %>%
      summarise(weekday_count = n()) %>%
      ggplot(aes(x = weekday, y = weekday_count)) +
      geom_line(size = 0.5, alpha = 0.7, color = "purple")  +
      geom_point(color = "purple") +
      labs(title = "Crime Counts by Weekday", x = "Weekday", y = "Count") +
      theme_minimal()

    ggplotly(weekday_data)

  } else if (input$victim_time == "Hourly") {
    hourly_data <- filtered_data %>%
      group_by(hour) %>%
      summarise(hour_count = n()) %>%
      ggplot(aes(x = hour, y = hour_count)) +
      geom_line(size = 0.5, alpha = 0.7, color = "orange") +
      geom_point(color = "orange") +
      labs(title = "Crime Counts by Hour", x = "Hour", y = "Count") +
      theme_minimal()

    ggplotly(hourly_data)
  }
})
```

### Chart C

```{r}
renderPlotly({
  filtered_data <- data3 %>%
    filter(area_name == input$filter_area)

  boxplot_chart <- ggplot(filtered_data, aes(x = area_name, y = vict_age)) +
    geom_boxplot(fill = "blue", alpha = 0.5) +
    labs(title = "Age Distribution by Area", x = "Area", y = "Age") +
    theme_minimal()

  ggplotly(boxplot_chart)
})
```

